# Generated by Django 5.2.8 on 2025-11-19 22:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_date', models.DateField()),
                ('day_number', models.IntegerField(default=1)),
                ('total_miles', models.IntegerField(default=0)),
                ('driver_name', models.CharField(default='John Doe', max_length=255)),
                ('carrier_name', models.CharField(default='ABC Trucking', max_length=255)),
                ('vehicle_number', models.CharField(default='TRK-001', max_length=50)),
                ('cycle_used', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total_driving_hours', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('total_on_duty_hours', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('total_off_duty_hours', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['trip', 'day_number'],
            },
        ),
        migrations.CreateModel(
            name='DutyStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('off_duty', 'Off Duty'), ('sleeper_berth', 'Sleeper Berth'), ('driving', 'Driving'), ('on_duty', 'On Duty (Not Driving)')], max_length=20)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('duration_hours', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('location', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('grid_start_hour', models.IntegerField(default=0)),
                ('grid_end_hour', models.IntegerField(default=0)),
                ('daily_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duty_statuses', to='eld.dailylog')),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_location', models.CharField(max_length=255)),
                ('pickup_location', models.CharField(max_length=255)),
                ('dropoff_location', models.CharField(max_length=255)),
                ('current_cycle_used', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total_distance', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('estimated_duration', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('total_days', models.IntegerField(default=1)),
                ('route_geometry', models.JSONField(blank=True, null=True)),
                ('route_summary', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='dailylog',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_logs', to='eld.trip'),
        ),
    ]
