# Generated by Django 5.2.8 on 2025-11-19 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eld', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='user',
        ),
    ]
