export const HOS_RULES = {
  DAILY_DRIVING_LIMIT: 11,
  DUTY_WINDOW_LIMIT: 14,
  CYCLE_LIMIT_8_DAY: 70,
  MIN_BREAK_DURATION: 0.5,
  BREAK_REQUIRED_AFTER: 8,
  MIN_OFF_DUTY: 10,
  RESTART_HOURS: 34,
};


const sampleTripsData = [

]